// Phase 0: remove the inline pages/continues arrays from index.html
// (data now lives in data/letters.json, generated by extract-letters.js)
const fs = require('fs');

let html = fs.readFileSync('index.html', 'utf8');

// 1. Remove the inline pages + continues arrays (replace with empty placeholder)
const re = /  var pages = \[[\s\S]*?\];\s*\n\s*var continues = \[[^\]]*\];/;
if (!re.test(html)) { console.error('pages/continues block not found'); process.exit(1); }
html = html.replace(re, '  var pages = [];');

// 2. Wrap envelope + dot building in functions (so they can run after JSON loads)
const envBlock = `  // build envelopes
  pages.forEach(function(pg, i){
    var b = document.createElement("button");
    b.className = "env";
    b.setAttribute("aria-label", "Open letter page " + (i+1) + " of 6");
    b.innerHTML =
      '<span class="env-flap"></span>' +
      '<span class="env-seal">' + (i+1) + '</span>' +
      '<span class="env-emoji">' + pg.emoji + '</span>';
    b.addEventListener("click", function(){ openReader(i); });
    envWrap.appendChild(b);
  });

  // build dots
  pages.forEach(function(_, i){
    var d = document.createElement("button");
    d.className = "dot";
    d.setAttribute("aria-label", "Go to page " + (i+1));
    d.addEventListener("click", function(){ render(i); });
    dotsWrap.appendChild(d);
  });`;

const envFn = `  function buildEnvelopes(){
    pages.forEach(function(pg, i){
      var b = document.createElement("button");
      b.className = "env";
      b.setAttribute("aria-label", "Open letter page " + (i+1) + " of " + pages.length);
      b.innerHTML =
        '<span class="env-flap"></span>' +
        '<span class="env-seal">' + (i+1) + '</span>' +
        '<span class="env-emoji">' + pg.emoji + '</span>';
      b.addEventListener("click", function(){ openReader(i); });
      envWrap.appendChild(b);
    });
  }

  function buildDots(){
    pages.forEach(function(_, i){
      var d = document.createElement("button");
      d.className = "dot";
      d.setAttribute("aria-label", "Go to page " + (i+1));
      d.addEventListener("click", function(){ render(i); });
      dotsWrap.appendChild(d);
    });
  }`;

if (!html.includes(envBlock)) { console.error('envelope block not found'); process.exit(1); }
html = html.replace(envBlock, envFn);

// 3. Add the JSON loader after the day-counter interval
const anchor = `  updateDayCount();
  setInterval(updateDayCount, 60 * 60 * 1000);`;
if (!html.includes(anchor)) { console.error('day counter anchor not found'); process.exit(1); }
html = html.replace(anchor, anchor + `

  // load the letters from data/letters.json (Phase 0: data moved out of the HTML)
  fetch("data/letters.json")
    .then(function(r){ if(!r.ok) throw new Error("HTTP " + r.status); return r.json(); })
    .then(function(data){
      pages = (data && data.letters) || [];
      buildEnvelopes();
      buildDots();
      updateDayCount();
    })
    .catch(function(err){
      console.error("Could not load letters:", err);
      var msg = document.createElement("p");
      msg.className = "hub-hint";
      msg.textContent = "the letters are still being folded… try again in a moment ♡";
      hub.appendChild(msg);
    });`);

// 4. renderPaper: use pg.continues instead of the removed continues array
const oldCont = `    if(continues[i]){
      var c = document.createElement("p");
      c.className = "continues";
      c.textContent = "flip for more →";
      paperBody.appendChild(c);
    }`;
const newCont = `    if(pg.continues){
      var c = document.createElement("p");
      c.className = "continues";
      c.textContent = "flip for more →";
      paperBody.appendChild(c);
    }`;
if (!html.includes(oldCont)) { console.error('continues block not found'); process.exit(1); }
html = html.replace(oldCont, newCont);

// 5. pageNoFld: dynamic page count
const oldNo = `    pageNoFld.textContent = (i+1) + " of 6";`;
const newNo = `    pageNoFld.textContent = (i+1) + " of " + pages.length;`;
if (!html.includes(oldNo)) { console.error('pageNoFld block not found'); process.exit(1); }
html = html.replace(oldNo, newNo);

fs.writeFileSync('index.html', html);
console.log('index.html updated successfully');
console.log('pages placeholder:', html.includes('var pages = [];'));
console.log('loader added:', html.includes('fetch("data/letters.json")'));
console.log('buildEnvelopes:', html.includes('function buildEnvelopes()'));
console.log('pg.continues:', html.includes('if(pg.continues)'));
console.log('dynamic pageNo:', html.includes('" of " + pages.length'));